#!/bin/bash
# The logic to stop your application should be put in this script.
cd ${OPENSHIFT_REPO_DIR}

if [[ -f "server.pid" ]]; then
  cd ${OPENSHIFT_DATA_DIR}mule-standalone-3.3.1/bin

  ./mule stop
fi
